<?php
//
// File generated by ... on the 2016-04-27T09:51:33+0630
// Please do not edit manually
//

/**
 * Classes and menus for sttgdc-template-mgmt (version 1.0.0)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */


/**
 * Persistent classes for a CMDB
 *
 * @copyright   Copyright (C) 2010-2012 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
class Template extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array
		(
			'category' => 'bizmodel,searchable,structure',
			'key_type' => 'autoincrement',
			'name_attcode' => 'template_name',
			'state_attcode' => '',
			'reconc_keys' => array('template_name'),
			'db_table' => 'sttgdc_template',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'icon' => utils::GetAbsoluteUrlModulesRoot().'sttgdc-template-mgmt/images/document.png',
		);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("template_name", array("allowed_values"=>null, "sql"=>'template_name', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("description", array("allowed_values"=>null, "sql"=>'description', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  0 => 'template_name',
  1 => 'description',
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'template_name',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'template_name',
  1 => 'description',
));

	}


}
//
// Menus
//
class MenuCreation_sttgdc_template_mgmt extends ModuleHandlerAPI
{
	public static function OnMenuCreation()
	{
		global $__comp_menus__; // ensure that the global variable is indeed global !
		$__comp_menus__['Catalogs'] = new TemplateMenuNode('Catalogs', '', $__comp_menus__['DataAdministration']->GetIndex(), 50);
		$__comp_menus__['Template'] = new OQLMenuNode('Template', "SELECT Template", $__comp_menus__['Catalogs']->GetIndex(), 100, true);
	}
} // class MenuCreation_sttgdc_template_mgmt
