<?php
//
// File generated by ... on the 2016-04-27T09:51:33+0630
// Please do not edit manually
//

/**
 * Classes and menus for sttgdc_variable (version 1.0.0)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */


/**
 * Persistent classes for a CMDB
 *
 * @copyright   Copyright (C) 2010-2012 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
class Variable extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array
		(
			'category' => 'bizmodel,searchable,structure',
			'key_type' => 'autoincrement',
			'name_attcode' => 'unassigned_after_percent_x',
			'state_attcode' => 'status',
			'reconc_keys' => array('unassigned_after_percent_x'),
			'db_table' => 'sttgdc_variable',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'icon' => utils::GetAbsoluteUrlModulesRoot().'sttgdc_variable/images/document.png',
		);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeEnum("status", array("allowed_values"=>new ValueSetEnum("modify"), "display_style"=>'list', "sql"=>'status', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeInteger("unassigned_after_percent_x", array("allowed_values"=>null, "sql"=>'unassigned_after_percent_x', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeInteger("unassigned_after_percent_y", array("allowed_values"=>null, "sql"=>'unassigned_after_percent_y', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeInteger("pending_after_value_k", array("allowed_values"=>null, "sql"=>'pending_after_value_k', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeInteger("pending_after_value_l", array("allowed_values"=>null, "sql"=>'pending_after_value_l', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeInteger("shift_after_percent_n", array("allowed_values"=>null, "sql"=>'shift_after_percent_n', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeInteger("shift_after_percent_m", array("allowed_values"=>null, "sql"=>'shift_after_percent_m', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("description_x", array("allowed_values"=>null, "sql"=>'description_x', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("description_y", array("allowed_values"=>null, "sql"=>'description_y', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("description_k", array("allowed_values"=>null, "sql"=>'description_k', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("description_l", array("allowed_values"=>null, "sql"=>'description_l', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("description_n", array("allowed_values"=>null, "sql"=>'description_n', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("description_m", array("allowed_values"=>null, "sql"=>'description_m', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));

		// Lifecycle (status attribute: status)
		//
		MetaModel::Init_DefineStimulus(new StimulusUserAction("ev_validate", array()));
		MetaModel::Init_DefineStimulus(new StimulusUserAction("ev_reject", array()));
		MetaModel::Init_DefineStimulus(new StimulusUserAction("ev_assign", array()));
		MetaModel::Init_DefineStimulus(new StimulusUserAction("ev_reopen", array()));
		MetaModel::Init_DefineStimulus(new StimulusUserAction("ev_plan", array()));
		MetaModel::Init_DefineStimulus(new StimulusUserAction("ev_approve", array()));
		MetaModel::Init_DefineStimulus(new StimulusUserAction("ev_replan", array()));
		MetaModel::Init_DefineStimulus(new StimulusUserAction("ev_notapprove", array()));
		MetaModel::Init_DefineStimulus(new StimulusUserAction("ev_implement", array()));
		MetaModel::Init_DefineStimulus(new StimulusUserAction("ev_monitor", array()));
		MetaModel::Init_DefineStimulus(new StimulusUserAction("ev_finish", array()));
		MetaModel::Init_DefineState(
			"modify",
			array(
				"attribute_inherit" => '',
				"attribute_list" => array(
					'description_x' => OPT_ATT_READONLY,
					'description_y' => OPT_ATT_READONLY,
					'description_k' => OPT_ATT_READONLY,
					'description_l' => OPT_ATT_READONLY,
					'description_n' => OPT_ATT_READONLY,
					'description_m' => OPT_ATT_READONLY,
				),
			)
		);


		MetaModel::Init_SetZListItems('details', array (
  'fieldset:Variable:baseinfo' => 
  array (
    0 => 'unassigned_after_percent_x',
    1 => 'unassigned_after_percent_y',
    2 => 'pending_after_value_k',
    3 => 'pending_after_value_l',
    4 => 'shift_after_percent_n',
    5 => 'shift_after_percent_m',
  ),
  'fieldset:Variable:descriptioninfo' => 
  array (
    0 => 'description_x',
    1 => 'description_y',
    2 => 'description_k',
    3 => 'description_l',
    4 => 'description_n',
    5 => 'description_m',
  ),
));

	}


}
//
// Menus
//
class MenuCreation_sttgdc_variable extends ModuleHandlerAPI
{
	public static function OnMenuCreation()
	{
		global $__comp_menus__; // ensure that the global variable is indeed global !
		$__comp_menus__['ConfigManagement'] = new MenuGroup('ConfigManagement', 20);
		$__comp_menus__['Variable'] = new ModifyObjectMenuNode('Variable', 11);
	}
} // class MenuCreation_sttgdc_variable
