<?php
//
// File generated by ... on the 2016-04-27T09:51:33+0630
// Please do not edit manually
//

/**
 * Classes and menus for sttgdc_email_template (version 1.0.0)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */


/**
 * Persistent classes for a CMDB
 *
 * @copyright   Copyright (C) 2010-2012 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
class EmailTemplate extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array
		(
			'category' => 'bizmodel,searchable,structure',
			'key_type' => 'autoincrement',
			'name_attcode' => 'subject',
			'state_attcode' => '',
			'reconc_keys' => array('subject'),
			'db_table' => 'sttgdc_email_template',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'icon' => utils::GetAbsoluteUrlModulesRoot().'sttgdc_email_template/images/doc.png',
		);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeExternalKey("template_id", array("targetclass"=>'Template', "allowed_values"=>new ValueSetObjects("SELECT Template"), "sql"=>'template_id', "is_null_allowed"=>true, "on_target_delete"=>DEL_MANUAL, "depends_on"=>array(), "display_style"=>'select', "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("subject", array("allowed_values"=>null, "sql"=>'subject', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("body", array("allowed_values"=>null, "sql"=>'body', "default_value"=>'', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  0 => 'template_id',
  1 => 'subject',
  2 => 'body',
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'subject',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'template_id',
  1 => 'subject',
  2 => 'body',
));

	}


}
//
// Menus
//
class MenuCreation_sttgdc_email_template extends ModuleHandlerAPI
{
	public static function OnMenuCreation()
	{
		global $__comp_menus__; // ensure that the global variable is indeed global !
		$__comp_menus__['Catalogs'] = new TemplateMenuNode('Catalogs', '', $__comp_menus__['DataAdministration']->GetIndex(), 50);
		$__comp_menus__['EmailTemplate'] = new OQLMenuNode('EmailTemplate', "SELECT EmailTemplate", $__comp_menus__['Catalogs']->GetIndex(), 110, true);
	}
} // class MenuCreation_sttgdc_email_template
